### ISSUE TITLE
I need some help here.

### ISSUE THREAD

**Issue by llUnknownl** [cgtinker/blendartrack#15]
If I scale up the scene, reference points will be useless because they are not in their original position (obviously).

Any ideas about how to work with a bigger scene? I feel uncomfortable working with small pieces.

![imagen](https://github.com/cgtinker/blendartrack/assets/118249487/44967245-5458-466b-a2f5-0c908fc291b6)

As you can see, its really small (the cube is a default cube).

**Comment by cgtinker** [comment]
Create an empty, parent all reference points and the camera to the empty. Then transform the empty to your likings. This way you can easily change the scale / move stuff around

**Comment by llUnknownl** [comment]
Oh, that worked perfectly! Thanks, that really helped me a lot.
