### ISSUE TITLE
My Android 10 device isn't supported

### ISSUE THREAD

**Issue by yestinlamptey** [cgtinker/blendartrack#4]
Dear team,

Thanks for building an awesome concept. I'd like to get started to test it but I cannot download from the Google Play store as it says my device is not supported.

It's a good phone, Huawei Nova 5T. 

Do you have any plans to release for this model?

Best regards,

Yestin

**Comment by cgtinker** [comment]
Hey Yestin,

Sorry for the late response, I checked at Huawei - sadly they don't plan to add ArCore-Support to your device which is required to run the application.

Best regards,
Denys

**Comment by yestinlamptey** [comment]
Thanks for the effort you went through to notify me. I am greatly disappointed although not surprised. It seems these nuances are what seperates the good from the great. Wasn't it Steve Jobs who said, if you care about software, you often make your own hardware?

If you could have any hardware in the world, for this app, what combination would it be and why haven't you built it yet? I have a deep interest in this technology and believe it will be an integral part of a larger project if you have the time to discuss.

All the best,

Yestin
