### ISSUE TITLE
Support for 3.1

### ISSUE THREAD

**Issue by patriciogonzalezvivo** [cgtinker/blendartrack#7]
Hi! First of all, thank you for all this work. Seams like a fantastic and "forward-looking" tool.
Seams the scrip it's still not ready for 3.1. Isn't that right? 

![Screenshot from 2022-03-20 14-36-07](https://user-images.githubusercontent.com/346914/159177421-67c79ec0-97c4-4280-a2bf-075cf4e87904.png)
l

**Comment by patriciogonzalezvivo** [comment]
Figure the issue. Wasn't that hard https://github.com/cgtinker/blendartrack/pull/8 

Thanks for this amazing addon!

**Comment by cgtinker** [comment]
Yea didn't add support yet - usually the updates lead to minor issues. 
I'll check your pull request soon, thanks! :)

**Comment by patriciogonzalezvivo** [comment]
Hi! Friendly feedback, usually issues are close when they are resolve, otherwise people will keep bringing them up. They are opportunities for collaboration and a back&forth. Closing them without resolution feels a bit rude. Cheers and thank you again.
